#!/usr/bin/env python3
"""
Fetch model pricing from OpenRouter and generate backend/memory/pricing_openrouter.py.

Background: The built-in pricing table (pricing.py PRICING_TABLE) is manually maintained and
only covers common models. OpenRouter's /api/v1/models aggregates official prices for 300+
models, serving as a fallback reference.
Usage:
    python3.11 scripts/update_openrouter_pricing.py            # fetch online
    python3.11 scripts/update_openrouter_pricing.py cache.json  # use local JSON

Generation rules:
  - OpenRouter prices are in "USD per token"; multiply by 1_000_000 to get per-1M-tokens price
  - Keys include the full id (e.g. "openai/gpt-4o"); the suffix after the slash (e.g. "gpt-4o")
    is only included when unique across the entire table to avoid price collisions from
    different providers with the same model name
  - input_cache_read is stored as cached_input; omitted when missing (price lookup falls back
    to the input price)

Copyright (c) 2026 Asterove
AGPL-3.0 License
"""

import json
import sys
import urllib.request
from collections import defaultdict
from pathlib import Path

API_URL = "https://openrouter.ai/api/v1/models"
OUTPUT = Path(__file__).resolve().parent.parent / "backend" / "memory" / "pricing_openrouter.py"

HEADER = '''"""
OpenRouter reference pricing table (auto-generated, do not edit manually).
Generated by scripts/update_openrouter_pricing.py, data source: {url}.
Unit: USD per 1M tokens. Lookup priority: user override > built-in table > local free > this table.
"""

from typing import Dict

OPENROUTER_PRICING: Dict[str, Dict[str, float]] = {{
'''


def load_models() -> list:
    if len(sys.argv) > 1:
        with open(sys.argv[1], encoding="utf-8") as f:
            return json.load(f)["data"]
    req = urllib.request.Request(API_URL, headers={"User-Agent": "astermem-pricing-sync"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))["data"]


def to_entry(pricing: dict) -> dict:
    def per_million(key: str):
        raw = pricing.get(key)
        if raw in (None, ""):
            return None
        return round(float(raw) * 1_000_000, 6)

    entry = {
        "input": per_million("prompt") or 0.0,
        "output": per_million("completion") or 0.0,
    }
    cached = per_million("input_cache_read")
    if cached is not None:
        entry["cached_input"] = cached
    return entry


def main() -> None:
    models = load_models()
    table: dict = {}
    suffix_candidates: dict = defaultdict(list)

    for m in models:
        model_id = m.get("id", "")
        pricing = m.get("pricing") or {}
        if not model_id:
            continue
        entry = to_entry(pricing)
        table[model_id.lower()] = entry
        if "/" in model_id:
            suffix = model_id.split("/", 1)[1].lower()
            # ":free" variants are excluded from suffix mapping to avoid misidentifying paid models as free
            if ":" not in suffix:
                suffix_candidates[suffix].append(entry)

    ambiguous = 0
    for suffix, entries in suffix_candidates.items():
        if suffix in table:
            continue
        unique = {json.dumps(e, sort_keys=True) for e in entries}
        if len(unique) == 1:
            table[suffix] = entries[0]
        else:
            ambiguous += 1

    lines = [HEADER.format(url=API_URL)]
    for key in sorted(table):
        entry = table[key]
        parts = [f'"input": {entry["input"]}', f'"output": {entry["output"]}']
        if "cached_input" in entry:
            parts.append(f'"cached_input": {entry["cached_input"]}')
        lines.append(f'    "{key}": {{{", ".join(parts)}}},\n')
    lines.append("}\n")
    OUTPUT.write_text("".join(lines), encoding="utf-8")
    print(f"✅ {len(models)} models → {len(table)} keys (skipped {ambiguous} ambiguous suffixes)")
    print(f"   Written to {OUTPUT}")


if __name__ == "__main__":
    main()
